### PR TITLE
Add env variable for dev server command options

### PR DESCRIPTION
**Pull request by charlie-wasp**
Implementation of #4 

One problem though: it's hard to choose reasonable name for environmental variable for this particular option. Any better ideas maybe?

### CODE REVIEW

**Comment by samuelsimoes** [comment]
First, thanks for the PR.

I liked the ENV var name, but I was thinking that would be nice if we use a ENV var for the whole command to boot the Webpack Dev Server because today you need the host option, tomorroy someone invoke the dev server from other folder and things like this, so I think that abstract the whole command in a ENV var would be a better path.

What do you think?

**Comment by charlie-wasp** [comment]
@samuelsimoes it sounds very reasonable, in fact I thought about this issue. Let's implement it like this, I'll update PR

**Comment by charlie-wasp** [comment]
@samuelsimoes what about ENV only for options, not the whole command? We would want the binary to always be the same, right? Giving option to override the whole command makes a breach, end user will be able to run arbitrary command. What do you think? I updated PR for this way

**Comment by charlie-wasp** [comment]
@samuelsimoes it's been a while, is everything fine?

**Comment by samuelsimoes** [comment]
@charlie-wasp sorry for the late response.

You definitely are right about the security concerns.

I was thinking. What are the flags that we can't define through config file? Host, for example, could be defined with the `config.devServer.host` option.

If we can define all webpack dev server flags through webpack config file, would be better always define there.

**Comment by charlie-wasp** [comment]
@samuelsimoes didn't know about that file, as a matter of fact, I have no prior experience with webpack. If this problem can be solved only with config file, it will be cool.

However, at the moment, I couldn't make it work. I'll try again, maybe my app is broken itself, and then I'll write back here

**Comment by charlie-wasp** [comment]
@samuelsimoes yep, you were right, we can use webpack config file for it. Sorry for your wasted time :(

**Comment by samuelsimoes** [comment]
@charlie-wasp no problem. I appreciate any try to help. 👍 

Since it's solved, closing.

**Pull request closed without merging**
